name: Qodana CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  qodana:
    name: Qodana (Community)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Qodana Scan (Community)
        uses: JetBrains/qodana-action@v2025.2
        with:
          args: --image jetbrains/qodana-python-community:2025.2
          use-caches: true
          pr-mode: false

      - name: List Qodana outputs (debug)
        if: ${{ always() }}
        run: |
          echo "=== Root dir ==="
          ls -lah
          echo "=== Qodana ==="
          ls -lah qodana || true
          echo "=== Qodana/results ==="
          ls -lah qodana/results || true

      - name: Upload SARIF from Qodana
        if: ${{ always() && hashFiles('qodana/results/qodana.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: qodana/results/qodana.sarif
          category: qodana
          wait-for-processing: true
