name: Qodana CI (Community)

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  qodana:
    name: Qodana (Community)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ВАЖНО: не используем --image, задаём линтер по идентификатору
      - name: Qodana Scan (Community)
        id: qscan
        uses: JetBrains/qodana-action@v2025.2
        with:
          # Явно определяем лinter ID вместо docker image
          args: >-
            --linter=qodana-python-community
            --within-docker=true
            --results-dir=qodana
          use-caches: true
          pr-mode: false

      # Диагностика — оставить на первых прогонах
      - name: List Qodana outputs (debug)
        if: ${{ always() }}
        run: |
          echo "=== Root dir ==="
          ls -lah
          echo "=== qodana ==="
          ls -lah qodana || true
          echo "=== qodana/results ==="
          ls -lah qodana/results || true

      - name: Upload SARIF from Qodana
        if: ${{ always() && hashFiles('qodana/results/qodana.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: qodana/results/qodana.sarif
          category: qodana
          wait-for-processing: true
